### ISSUE TITLE
if the user presses 'cancel' within WorldPay the order still get marked as paid

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/worldpay-plugin-for-nopcommerce#3]
See pull request (https://github.com/nopSolutions/worldpay-plugin-for-nopcommerce/pull/1 and https://github.com/nopSolutions/worldpay-plugin-for-nopcommerce/pull/4). But it's not finished (see comments)

**Comment by mirzakhalid82** [comment]
Can we please have compiled version of this plugin with this fix for nopCommerce 3.60.
Kind Rgards

**Comment by AndreiMaz** [comment]
@skoshelev посмотри потом тоже, когда будешь обновлять
